DATASOURCE_MYSQL_URL: jdbc:mysql://localhost:3306/nh-monolithic-application?allowPublicKeyRetrieval=true&useSSL=false
DATASOURCE_MYSQL_USERNAME: root
DATASOURCE_MYSQL_PASSWORD: P@ssw0rd
DATASOURCE_MYSQL_DRIVER: com.mysql.cj.jdbc.Driver

MINIO_ENDPOINT_URL: http://localhost:9000
MINIO_ACCESS_KEY: FKgvhmB6Nsrgp9itFtBX
MINIO_ACCESS_SECRET: TWDijrtCByfRq7f6dOQ1d075M9mOmIgeerKl8CFK

INFLUX_DATABASE_URL: http://localhost:8086?readTimeout=30000&bucket=nh-monolithic-application&org=new-horizon
INFLUX_USERNAME: nh-monolithic-application
INFLUX_PASSWORD: P@ssw0rd

MQTT_USERNAME: nh-monolithic-application
MQTT_PASSWORD: P@ssw0rd

EXAM_RESULT_UPLOAD_PATH: minio:patient/{0}/{1}/{2}{3}
EMERGENCY_ROOM_DOCUMENT_UPLOAD_PATH: minio:patient/{0}/{1}/emergency-room-document/{2}{3}


com:
  new-horizon:
    mqtt:
      bootstrap-servers:
        - tcp://localhost:1883
spring:
  security:
    user:
      name: microservice
      password: P@ssw0rd
server:
  port: 8000