@startuml
actor "Monitoring Device" as monitoringDevice #red
participant "NewHorizon RabbitMQ Support Service" as nhRabbitSupportService
queue "/monitoring/{deviceId}" as parameterMonitoringQueue

monitoringDevice -> nhRabbitSupportService: POST@/nh-rabbit-support-service/auth
note right
    The monitoring device ask username and password
    using its own configurations and infos
    to retrieve username and password
    to join the queue
end note
nhRabbitSupportService -> monitoringDevice: Return username and password
monitoringDevice -->o parameterMonitoringQueue: Send parameter to the queue
note right
    Parameters are:
        - PING - for keep alive
        - ECG - cardiac activity
        - NIBP - blood pressure
        - RESP - respiration
        - SpO2 - blood saturation
        - TEMP - body temperature
end note

@enduml