name: CD
# Triggers
on:
  workflow_dispatch: # Manual trigger from the Actions tab
    inputs:
      environment:
        description: "Select the environment"
        type: choice
        options:
          - dev
          - test
          - preprod
          - prod
        required: false
        default: dev
      container-image:
        description: "Select the container image to patch in manifest"
        type: string
        required: true

permissions:
  contents: write
  packages: write
  pages: write
  actions: write

jobs:
  ci:
    secrets: inherit
    uses: pingmyheart/Ping-Actions/.github/workflows/cd-dispatcher.yml@main
    with:
      country: .
      farm: .
      environment: ${{ github.event.inputs.environment }}
      container-image: ${{ github.event.inputs.container-image}}
      manifest-repo: New-Horizon-NH/nh-manifest